import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const initialReports = [
  { id: 1, type: 'Mid-Term Progress', class: '10A', generatedBy: 'Ms. Priya Sharma', date: '2026-05-10', status: 'Final' },
  { id: 2, type: 'Annual Performance', class: 'All Classes', generatedBy: 'Principal', date: '2026-04-28', status: 'Final' },
  { id: 3, type: 'Attendance Summary', class: '9B', generatedBy: 'Mr. Rajesh Kumar', date: '2026-05-05', status: 'Draft' },
  { id: 4, type: 'Subject Analysis', class: 'Mathematics', generatedBy: 'Ms. Priya Sharma', date: '2026-05-01', status: 'Final' },
  { id: 5, type: 'Quarterly Report', class: 'All Classes', generatedBy: 'Principal', date: '2026-03-31', status: 'Final' },
  { id: 6, type: 'Behavior Report', class: '8A', generatedBy: 'Mr. Vikram Singh', date: '2026-05-12', status: 'Draft' },
];

export default function Reports() {
  const navigate = useNavigate();
  const [reports, setReports] = useState(initialReports);
  const [viewReport, setViewReport] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [newType, setNewType] = useState('');
  const [newClass, setNewClass] = useState('');
  const [newDate, setNewDate] = useState(new Date().toISOString().split('T')[0]);
  const [newGeneratedBy, setNewGeneratedBy] = useState('Principal');
  const [typeFilter, setTypeFilter] = useState('');
  const [classFilter, setClassFilter] = useState('');

  const filteredReports = reports.filter(r => {
    const matchType = !typeFilter || r.type === typeFilter;
    const matchClass = !classFilter || r.class === classFilter;
    return matchType && matchClass;
  });

  const handleGenerate = () => {
    if (!newType) return;
    const report = { id: Date.now(), type: newType, class: newClass || 'All Classes', generatedBy: newGeneratedBy, date: newDate, status: 'Draft' };
    setReports([report, ...reports]);
    setNewType(''); setNewClass(''); setNewDate(new Date().toISOString().split('T')[0]); setNewGeneratedBy('Principal'); setShowForm(false);
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <div className="flex items-center gap-4">
          <button onClick={() => navigate('/dashboard/principal')} className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">
            <svg className="w-5 h-5 text-gray-600 dark:text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </button>
          <div>
            <h1>Academic Reports</h1>
            <p>Generate and manage academic reports.</p>
          </div>
        </div>
      </div>

      <div className="flex justify-between items-center mb-6">
        <div className="flex gap-3">
          <select className="input-field w-44" value={typeFilter} onChange={e => setTypeFilter(e.target.value)}>
            <option value="">All Types</option>
            <option>Mid-Term Progress</option>
            <option>Annual Performance</option>
            <option>Attendance Summary</option>
            <option>Subject Analysis</option>
            <option>Quarterly Report</option>
          </select>
          <select className="input-field w-36" value={classFilter} onChange={e => setClassFilter(e.target.value)}>
            <option value="">All Classes</option>
            <option>10A</option>
            <option>10B</option>
            <option>9A</option>
            <option>9B</option>
            <option>8A</option>
          </select>
        </div>
        <button onClick={() => setShowForm(!showForm)} className="btn-primary">+ Generate Report</button>
      </div>

      {showForm && (
        <div className="card mb-6 p-4">
          <h3 className="font-semibold mb-4">Generate Report</h3>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
            <input value={newType} onChange={e => setNewType(e.target.value)} className="input-field" placeholder="Report type" />
            <input value={newClass} onChange={e => setNewClass(e.target.value)} className="input-field" placeholder="Class (optional)" />
            <input type="date" value={newDate} onChange={e => setNewDate(e.target.value)} className="input-field" />
            <input value={newGeneratedBy} onChange={e => setNewGeneratedBy(e.target.value)} className="input-field" placeholder="Generated by" />
            <div className="flex gap-2 md:col-span-4">
              <button onClick={handleGenerate} className="btn-primary flex-1">Generate</button>
              <button onClick={() => setShowForm(false)} className="btn-outline flex-1">Cancel</button>
            </div>
          </div>
        </div>
      )}

      <div className="card overflow-x-auto">
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-gray-200 dark:border-gray-700">
              <th className="py-3 px-4 font-semibold text-sm">Report Type</th>
              <th className="py-3 px-4 font-semibold text-sm">Class</th>
              <th className="py-3 px-4 font-semibold text-sm">Generated By</th>
              <th className="py-3 px-4 font-semibold text-sm">Date</th>
              <th className="py-3 px-4 font-semibold text-sm">Status</th>
              <th className="py-3 px-4 font-semibold text-sm">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.map((report) => (
              <tr key={report.id} className="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                <td className="py-3 px-4 font-medium">{report.type}</td>
                <td className="py-3 px-4">{report.class}</td>
                <td className="py-3 px-4">{report.generatedBy}</td>
                <td className="py-3 px-4">{report.date}</td>
                <td className="py-3 px-4">
                  <span className={`badge-${report.status === 'Final' ? 'success' : 'warning'}`}>
                    {report.status}
                  </span>
                </td>
                <td className="py-3 px-4 space-x-2">
                  <button onClick={() => setViewReport(report)} className="text-blue-600 hover:underline text-sm">View</button>
                  <button onClick={() => alert(`Downloading ${report.type}...`)} className="text-blue-600 hover:underline text-sm">Download</button>
                  <button onClick={() => { if (confirm('Delete this report?')) setReports(reports.filter(r => r.id !== report.id)); }} className="text-red-600 hover:underline text-sm">Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {viewReport && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setViewReport(null)}>
          <div className="bg-white dark:bg-gray-800 rounded-xl p-6 max-w-md w-full mx-4 shadow-xl" onClick={e => e.stopPropagation()}>
            <h3 className="text-lg font-bold mb-4">{viewReport.type}</h3>
            <div className="space-y-2 text-sm">
              <p><span className="font-medium">Class:</span> {viewReport.class}</p>
              <p><span className="font-medium">Generated By:</span> {viewReport.generatedBy}</p>
              <p><span className="font-medium">Date:</span> {viewReport.date}</p>
              <p><span className="font-medium">Status:</span> {viewReport.status}</p>
            </div>
            <button onClick={() => setViewReport(null)} className="btn-primary mt-4 w-full">Close</button>
          </div>
        </div>
      )}
    </div>
  );
}
