const ROLES = {
  super_admin: 'super_admin',
  school_admin: 'school_admin',
  principal: 'principal',
  vice_principal: 'vice_principal',
  admin_officer: 'admin_officer',
  accountant: 'accountant',
  teacher: 'teacher',
  class_teacher: 'class_teacher',
  librarian: 'librarian',
  receptionist: 'receptionist',
  student: 'student',
  parent: 'parent',
  transport: 'transport',
  hostel_warden: 'hostel_warden',
}

const ROLE_DISPLAY_NAMES = {
  super_admin: 'Super Admin',
  school_admin: 'School Admin',
  principal: 'Principal',
  vice_principal: 'Vice Principal',
  admin_officer: 'Admin Officer',
  accountant: 'Accountant',
  teacher: 'Teacher',
  class_teacher: 'Class Teacher',
  librarian: 'Librarian',
  receptionist: 'Receptionist',
  student: 'Student',
  parent: 'Parent',
  transport: 'Transport Manager',
  hostel_warden: 'Hostel Warden',
}

const ROLE_ICONS = {
  super_admin: '🛡️',
  school_admin: '🏫',
  principal: '👔',
  vice_principal: '👔',
  admin_officer: '📋',
  accountant: '💰',
  teacher: '👨‍🏫',
  class_teacher: '👩‍🏫',
  librarian: '📚',
  receptionist: '📞',
  student: '🎓',
  parent: '👨‍👩‍👧‍👦',
  transport: '🚌',
  hostel_warden: '🏠',
}

const MODULES = {
  dashboard: 'Dashboard',
  schoolSettings: 'School Settings',
  branchManagement: 'Branch Management',
  userManagement: 'User Management',
  studentAdmission: 'Student Admission',
  studentRecords: 'Student Records',
  staffManagement: 'Staff Management',
  attendance: 'Attendance',
  timetable: 'Timetable',
  homework: 'Homework',
  exams: 'Exams',
  marksReportCards: 'Marks & Report Cards',
  feeCollection: 'Fee Collection',
  accounts: 'Accounts',
  salary: 'Salary',
  library: 'Library',
  transport: 'Transport',
  hostel: 'Hostel',
  inventory: 'Inventory',
  certificates: 'Certificates',
  noticeBoard: 'Notice Board',
  smsEmail: 'SMS / Email',
  events: 'Events',
  complaints: 'Complaints',
  documents: 'Documents',
  reports: 'Reports',
  auditLogs: 'Audit Logs',
  backupRestore: 'Backup & Restore',
}

const PERM_LEVELS = {
  none: 'none',
  view: 'view',
  full: 'full',
}

const ROLE_HIERARCHY = [
  'super_admin',
  'school_admin',
  'principal',
  'vice_principal',
  'admin_officer',
  'accountant',
  'class_teacher',
  'teacher',
  'librarian',
  'receptionist',
  'transport',
  'hostel_warden',
  'student',
  'parent',
]

const PERMISSION_MATRIX = {
  super_admin: {
    dashboard: 'full',
    schoolSettings: 'full',
    branchManagement: 'full',
    userManagement: 'full',
    studentAdmission: 'full',
    studentRecords: 'full',
    staffManagement: 'full',
    attendance: 'full',
    timetable: 'full',
    homework: 'full',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'full',
    accounts: 'full',
    salary: 'full',
    library: 'full',
    transport: 'full',
    hostel: 'full',
    inventory: 'full',
    certificates: 'full',
    noticeBoard: 'full',
    smsEmail: 'full',
    events: 'full',
    complaints: 'full',
    documents: 'full',
    reports: 'full',
    auditLogs: 'full',
    backupRestore: 'full',
  },
  school_admin: {
    dashboard: 'full',
    schoolSettings: 'full',
    branchManagement: 'full',
    userManagement: 'full',
    studentAdmission: 'full',
    studentRecords: 'full',
    staffManagement: 'full',
    attendance: 'full',
    timetable: 'full',
    homework: 'full',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'full',
    accounts: 'full',
    salary: 'full',
    library: 'full',
    transport: 'full',
    hostel: 'full',
    inventory: 'full',
    certificates: 'full',
    noticeBoard: 'full',
    smsEmail: 'full',
    events: 'full',
    complaints: 'full',
    documents: 'full',
    reports: 'full',
    auditLogs: 'view',
    backupRestore: 'view',
  },
  principal: {
    dashboard: 'full',
    schoolSettings: 'view',
    branchManagement: 'view',
    userManagement: 'full',
    studentAdmission: 'full',
    studentRecords: 'full',
    staffManagement: 'full',
    attendance: 'full',
    timetable: 'full',
    homework: 'view',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'view',
    accounts: 'view',
    salary: 'view',
    library: 'view',
    transport: 'view',
    hostel: 'view',
    inventory: 'view',
    certificates: 'full',
    noticeBoard: 'full',
    smsEmail: 'full',
    events: 'full',
    complaints: 'full',
    documents: 'full',
    reports: 'full',
    auditLogs: 'view',
    backupRestore: 'none',
  },
  vice_principal: {
    dashboard: 'full',
    schoolSettings: 'view',
    branchManagement: 'none',
    userManagement: 'view',
    studentAdmission: 'full',
    studentRecords: 'full',
    staffManagement: 'view',
    attendance: 'full',
    timetable: 'full',
    homework: 'view',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'none',
    library: 'view',
    transport: 'view',
    hostel: 'view',
    inventory: 'none',
    certificates: 'view',
    noticeBoard: 'full',
    smsEmail: 'view',
    events: 'full',
    complaints: 'view',
    documents: 'view',
    reports: 'full',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  admin_officer: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'full',
    studentRecords: 'full',
    staffManagement: 'view',
    attendance: 'view',
    timetable: 'full',
    homework: 'none',
    exams: 'view',
    marksReportCards: 'view',
    feeCollection: 'view',
    accounts: 'none',
    salary: 'none',
    library: 'none',
    transport: 'none',
    hostel: 'none',
    inventory: 'full',
    certificates: 'full',
    noticeBoard: 'full',
    smsEmail: 'full',
    events: 'full',
    complaints: 'full',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  accountant: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'view',
    studentRecords: 'view',
    staffManagement: 'none',
    attendance: 'none',
    timetable: 'none',
    homework: 'none',
    exams: 'none',
    marksReportCards: 'none',
    feeCollection: 'full',
    accounts: 'full',
    salary: 'full',
    library: 'none',
    transport: 'none',
    hostel: 'none',
    inventory: 'view',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'none',
    events: 'none',
    complaints: 'none',
    documents: 'view',
    reports: 'full',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  teacher: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'none',
    studentRecords: 'view',
    staffManagement: 'view',
    attendance: 'full',
    timetable: 'view',
    homework: 'full',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'view',
    library: 'view',
    transport: 'view',
    hostel: 'none',
    inventory: 'none',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'view',
    events: 'view',
    complaints: 'view',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  class_teacher: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'none',
    studentRecords: 'full',
    staffManagement: 'none',
    attendance: 'full',
    timetable: 'view',
    homework: 'full',
    exams: 'full',
    marksReportCards: 'full',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'view',
    library: 'view',
    transport: 'view',
    hostel: 'none',
    inventory: 'none',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'view',
    events: 'view',
    complaints: 'view',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  librarian: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'none',
    studentRecords: 'none',
    staffManagement: 'none',
    attendance: 'none',
    timetable: 'none',
    homework: 'none',
    exams: 'none',
    marksReportCards: 'none',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'view',
    library: 'full',
    transport: 'none',
    hostel: 'none',
    inventory: 'view',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'none',
    events: 'view',
    complaints: 'none',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  receptionist: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'full',
    studentRecords: 'view',
    staffManagement: 'none',
    attendance: 'none',
    timetable: 'view',
    homework: 'none',
    exams: 'none',
    marksReportCards: 'none',
    feeCollection: 'full',
    accounts: 'none',
    salary: 'view',
    library: 'none',
    transport: 'view',
    hostel: 'none',
    inventory: 'none',
    certificates: 'full',
    noticeBoard: 'view',
    smsEmail: 'full',
    events: 'view',
    complaints: 'full',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  student: {
    dashboard: 'view',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'view',
    studentRecords: 'view',
    staffManagement: 'none',
    attendance: 'view',
    timetable: 'view',
    homework: 'view',
    exams: 'view',
    marksReportCards: 'view',
    feeCollection: 'view',
    accounts: 'none',
    salary: 'none',
    library: 'view',
    transport: 'view',
    hostel: 'view',
    inventory: 'none',
    certificates: 'view',
    noticeBoard: 'view',
    smsEmail: 'none',
    events: 'view',
    complaints: 'create',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  parent: {
    dashboard: 'view',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'view',
    studentRecords: 'view',
    staffManagement: 'none',
    attendance: 'view',
    timetable: 'view',
    homework: 'view',
    exams: 'view',
    marksReportCards: 'view',
    feeCollection: 'view',
    accounts: 'none',
    salary: 'none',
    library: 'view',
    transport: 'view',
    hostel: 'view',
    inventory: 'none',
    certificates: 'view',
    noticeBoard: 'view',
    smsEmail: 'view',
    events: 'view',
    complaints: 'create',
    documents: 'view',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  transport: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'none',
    studentRecords: 'none',
    staffManagement: 'none',
    attendance: 'none',
    timetable: 'none',
    homework: 'none',
    exams: 'none',
    marksReportCards: 'none',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'none',
    library: 'none',
    transport: 'full',
    hostel: 'none',
    inventory: 'none',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'none',
    events: 'view',
    complaints: 'none',
    documents: 'none',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
  hostel_warden: {
    dashboard: 'full',
    schoolSettings: 'none',
    branchManagement: 'none',
    userManagement: 'none',
    studentAdmission: 'none',
    studentRecords: 'view',
    staffManagement: 'none',
    attendance: 'none',
    timetable: 'none',
    homework: 'none',
    exams: 'none',
    marksReportCards: 'none',
    feeCollection: 'none',
    accounts: 'none',
    salary: 'none',
    library: 'none',
    transport: 'none',
    hostel: 'full',
    inventory: 'view',
    certificates: 'none',
    noticeBoard: 'view',
    smsEmail: 'none',
    events: 'view',
    complaints: 'none',
    documents: 'none',
    reports: 'view',
    auditLogs: 'none',
    backupRestore: 'none',
  },
}

function checkPermission(role, module, action) {
  const perm = PERMISSION_MATRIX[role]?.[module] || 'none'
  if (perm === 'full') return true
  if (action === 'view' && (perm === 'view' || perm === 'create')) return true
  if (action === 'create' && (perm === 'create' || perm === 'full')) return true
  return false
}

function getPermissionLevel(role, module) {
  return PERMISSION_MATRIX[role]?.[module] || 'none'
}

function hasFullAccess(role, module) {
  return getPermissionLevel(role, module) === 'full'
}

function canView(role, module) {
  return checkPermission(role, module, 'view')
}

function canCreate(role, module) {
  return checkPermission(role, module, 'create')
}

function canEdit(role, module) {
  return getPermissionLevel(role, module) === 'full'
}

function canDelete(role, module) {
  return getPermissionLevel(role, module) === 'full'
}

function isRoleHigherOrEqual(currentRole, targetRole) {
  const currentIdx = ROLE_HIERARCHY.indexOf(currentRole)
  const targetIdx = ROLE_HIERARCHY.indexOf(targetRole)
  if (currentIdx === -1 || targetIdx === -1) return false
  return currentIdx <= targetIdx
}

export {
  ROLES,
  ROLE_DISPLAY_NAMES,
  ROLE_ICONS,
  MODULES,
  PERM_LEVELS,
  ROLE_HIERARCHY,
  PERMISSION_MATRIX,
  checkPermission,
  getPermissionLevel,
  hasFullAccess,
  canView,
  canCreate,
  canEdit,
  canDelete,
  isRoleHigherOrEqual,
}
